config/routes.rb
ProgramacaoLinear::Application.routes.draw do
  get "home/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "programa_linear/index"

  get "programa_linear/novo"

  get "programa_linear/exibir_resultado"

  post "programa_linear/solucionar_problema"

  get "programa_linear/abrir_exemplo"

  get "programa_linear/visualizar_exemplo"
  
  get "programa_linear/solucionar_exemplo"

   root :to => 'home#index'

end

app/models/programa_linear.rb
class ProgramaLinear < ActiveRecord::Base
  has_one :funcao_objetivo
  has_many :restricoes
  attr_accessible :descricao, :nome, :numero_variavel, :numero_restricao, :funcao_objetivo_attributes, :restricoes_attributes
  
  accepts_nested_attributes_for :restricoes
  accepts_nested_attributes_for :funcao_objetivo
   
end

app/controllers/programa_linear_controller.rb
class ProgramaLinearController < ApplicationController
  
  include Simplex
  
  def index
 
    
  end
  
  def novo
    
    @programa_linear = ProgramaLinear.new
    @programa_linear.numero_variavel = params[:numero_variaveis]
    @programa_linear.numero_restricao = params[:numero_restricoes]
      
    @programa_linear.funcao_objetivo = FuncaoObjetivo.new 
    @programa_linear.numero_variavel.times { @programa_linear.funcao_objetivo.coeficiente_funcao_objetivo.build }
    @programa_linear.numero_variavel.times { @programa_linear.funcao_objetivo.operador_aritmetico_funcao_objetivos.build }
       
         
    @programa_linear.numero_restricao.times do
      restricao =  @programa_linear.restricoes.build
      @programa_linear.numero_variavel.times { restricao.coeficiente_restricoes.build }
        
    end

    respond_to do |format|
      format.html 
      format.json { render json: @programa_linear  }
    end
    
  end
  
  

  def exibir_resultado
    respond_to do |formato|
         formato.html { render html:  @programacao_linear }
         formato.json { render json:  @programacao_linear }
       end
    
   
  end

  def solucionar_problema
    
    @programa_linear = ProgramaLinear.new(params[:programa_linear])
      
    @programa_linear.numero_variavel =  @programa_linear.funcao_objetivo.coeficiente_funcao_objetivo.length
    @programa_linear.numero_restricao = @programa_linear.restricoes.length
    
    @coeficiente_objetivo = Array.new()
    @constante_restricao = Array.new()
    @coeficientes_restricoes = Array.new(@programa_linear.numero_restricao) { Array.new(@programa_linear.numero_variavel) }
      
    @programa_linear.funcao_objetivo.coeficiente_funcao_objetivo.each do | coeficiente |     
      if @programa_linear.funcao_objetivo.tipo_otimizacao_id == 1 then
      
        @coeficiente_objetivo.push(coeficiente.valor)
      else
        @coeficiente_objetivo.push((coeficiente.valor * -1))
      end
    end
    
    @programa_linear.restricoes.each do | coeficiente |
      @constante_restricao.push(coeficiente.constante)
    end
    
          
    for i in 0..@programa_linear.numero_restricao-1
      for j in 0..@programa_linear.numero_variavel-1      
        @coeficientes_restricoes[i][j] = @programa_linear.restricoes[i].coeficiente_restricoes[j].valor
      end
    end
  
    @programacao_linear = ProgramacaoLinear.new(@coeficientes_restricoes, @constante_restricao, @coeficiente_objetivo)
    @programacao_linear.SolucionaProblema
    
    session[:programacao_linear] = @programacao_linear
      
    redirect_to :controller => 'programa_linear', :action => 'exibir_resultado', :d => @programacao_linear
  end

  def abrir_exemplo
    @programa_linear = ProgramaLinear.all
    
    respond_to do |format|
       format.html
       format.json { render json: @programa_linear }
    end
    
  end

  def visualizar_exemplo
    @programa_linear = ProgramaLinear.find(params[:format])
    #render :text => @programa_linear.restricoes.inspect
  end
  
  
  def solucionar_exemplo
    @programa_linear = ProgramaLinear.find(params[:id])
    
    @programa_linear.numero_variavel =  @programa_linear.funcao_objetivo.coeficiente_funcao_objetivo.length
       @programa_linear.numero_restricao = @programa_linear.restricoes.length
       
       @coeficiente_objetivo = Array.new()
       @constante_restricao = Array.new()
       @coeficientes_restricoes = Array.new(@programa_linear.numero_restricao) { Array.new(@programa_linear.numero_variavel) }
         
       @programa_linear.funcao_objetivo.coeficiente_funcao_objetivo.each do | coeficiente |     
         if @programa_linear.funcao_objetivo.tipo_otimizacao_id == 1 then
         
           @coeficiente_objetivo.push(coeficiente.valor)
         else
           @coeficiente_objetivo.push((coeficiente.valor * -1))
         end
       end
       
       @programa_linear.restricoes.each do | coeficiente |
         @constante_restricao.push(coeficiente.constante)
       end
       
             
       for i in 0..@programa_linear.numero_restricao-1
         for j in 0..@programa_linear.numero_variavel-1      
           @coeficientes_restricoes[i][j] = @programa_linear.restricoes[i].coeficiente_restricoes[j].valor
         end
       end
     
       @programacao_linear = ProgramacaoLinear.new(@coeficientes_restricoes, @constante_restricao, @coeficiente_objetivo)
       @programacao_linear.SolucionaProblema
       
       session[:programacao_linear] = @programacao_linear
         
       redirect_to :controller => 'programa_linear', :action => 'exibir_resultado', :d => @programacao_linear   
  end
  
  
  
  
  
  
  
  
  
  
  
end

app/helpers/programa_linear_helper.rb
module ProgramaLinearHelper
end

app/views/programa_linear/abrir_exemplo.html.erb
<div id="container-conteudo-principal" class="azul">
<header>
	<h2>Programação Linear</h2>
	<h3>Exemplos</h3>
	<hr />
</header>

<article>
	<table>
	<thead>
		<tr>
			<th class="coluna-id">ID</th>
			<th class="coluna-nome">Nome</th>
			<th class="coluna-opcao"></th>
		</tr>
	</thead>
	<tbody>
		<% @programa_linear.each do |programa| %>
			<tr>
				<td class="coluna-id"><%= programa.id %></td>
				<td class="coluna-nome"><%= link_to programa.nome, programa_linear_visualizar_exemplo_path(programa) %></td>
				<td class="coluna-opcao"><%= link_to 'Abrir', programa_linear_visualizar_exemplo_path(programa) %></td>
			</tr>
		<% end %>
	</tbody>
</table>
<br />	
</article>

</div>

<footer>
	<nav>
		<ul>
			<li><%= link_to "Voltar", home_index_path %></li>
			<li><%= link_to "Novo", programa_linear_index_path %></li>	
		</ul>	
	</nav>	
</footer>

app/views/programa_linear/exibir_resultado.html.erb
<div id="container-conteudo-principal" class="azul">
<header>
	<h2>Programação Linear</h2>
	<h3>Resultado - <span>Algoritmo Simplex</span></h3>
	<hr />
</header>

<article>
<table id="tabela-resultados">
<thead>
  <tr>
    <% for i in 0..session[:programacao_linear].numeroDeCoeficientes + session[:programacao_linear].numeroDeRestricoes %>
		<%= content_tag(:th) %>
    <% end %>
  </tr>
</thead>
<tbody>
<% for i in 0..session[:programacao_linear].numeroDeRestricoes %>
	<tr>
		<% for j in 0..session[:programacao_linear].numeroDeCoeficientes + session[:programacao_linear].numeroDeRestricoes %>
			<%= content_tag(:td, session[:programacao_linear].programaLinearAuxiliar[i][j])%>
		<% end %>
	</tr>
<% end %>
</tbody>
</table>

<div>
	
	<ul>
		<li><label>Valor Ótimo: </label></li>
		<li><%= content_tag(:span, session[:programacao_linear].ValorObjetivoOtimo())%></li>
	</ul>
	<ul>
		<% for i in 0..session[:programacao_linear].numeroDeRestricoes-1 %>
		
			<% if session[:programacao_linear].variaveisBasicas[i] < session[:programacao_linear].numeroDeCoeficientes %>
		    	<%=content_tag(:li, content_tag(:i, "X") + content_tag(:sub, (session[:programacao_linear].variaveisBasicas[i] + 1).to_s) + "  =  " + session[:programacao_linear].programaLinearAuxiliar[i][session[:programacao_linear].numeroDeRestricoes + session[:programacao_linear].numeroDeCoeficientes].to_s)%>
			<% end %>
    	<% end %>
	</ul>
</div>
</article>
</div>

<footer>
	<nav>
		<ul>
			<li><%= link_to "Início", home_index_path %></li>
			<li><%= link_to "Novo", programa_linear_index_path %></li>	
		</ul>	
	</nav>	
</footer>

app/views/programa_linear/index.html.erb
<div id="container-conteudo-principal" class="azul">
	
<header>
	<h2>Programação Linear</h2>
	<h3>Configurações</h3>
	<hr />
</header>

<article>
<%= form_tag("novo", :method => "get") do %>
	<fieldset>
		<legend>Configurações</legend>
		
		<%= label_tag(:numero_variaveis, "Número de Variáveis: ") %>
		<%= text_field_tag :numero_variaveis, "", :class => 'campo-numero-variavel', :autofocus => true %>
		<br />
		<%= label_tag(:numero_restricoes, "Número de Restrições: ") %>
		<%= text_field_tag :numero_restricoes, "", :class => 'campo-numero-restricao' %>
		
	</fieldset>
		<%= submit_tag "Confirmar", :class => 'botao botao-azul' %>
<% end %>
	
</article>
</div>



<footer>
	<nav>
		<ul>
			<li><%= link_to "Voltar", home_index_path %></li>	
		</ul>	
	</nav>	
</footer>

app/views/programa_linear/novo.html.erb
<div id="container-conteudo-principal" class="azul">
<header>
	<h2>Programação Linear</h2>
	<h3>Novo Programa Linear</h3>
	<hr />	
</header>

<article>
	
<%= form_for @programa_linear, :onload => 'enumera_variaveis()', :url => { :action => "solucionar_problema" } do |f|  %>
<fieldset>	
	<legend>Programa Linear</legend>
	<%= f.label  :nome %>
	<%= f.text_field  :nome, :class => 'campo-nome', :autofocus => true %><br />
	
	<%= f.label  :descricao %><br />
	<%= f.text_area :descricao %><br />
</fieldset>

<fieldset>	
	<legend>Função Objetivo</legend>
	
	
	<for>
	
	<%= f.fields_for :funcao_objetivo do |campo_funcao| %>
		<ul>
			<li><%= campo_funcao.collection_select :tipo_otimizacao_id, TipoOtimizacao.all, :id, :nome %></li>
				
			<%= campo_funcao.fields_for :coeficiente_funcao_objetivo do |campo_coeficiente| %>
				<%=content_tag(:li, campo_coeficiente.text_field(:valor))%>
				
				
				<%=content_tag(:li, content_tag(:i, "X") + content_tag(:sub, 1)) %>
				
			<% end %>
		</ul>
	<% end %>
</fieldset>

<fieldset>	
	<legend>Restrições</legend>
	
	<%= f.fields_for :restricoes do |campo_restricao, i| %>
		<ul>
			
			<%= campo_restricao.fields_for :coeficiente_restricoes do |campo_coeficiente| %>
				<%=content_tag(:li, campo_coeficiente.text_field(:valor))%>
				<%=content_tag(:li, content_tag(:i, "X") + content_tag(:sub, 1))%>
			<% end %>
			
		
			<li><%= campo_restricao.collection_select :operador_sentencial_id, OperadorSentencial.all, :id, :simbolo %></li>
			<li><%= campo_restricao.text_field :constante %></li>
				
		</ul>
	<% end %>

</fieldset>


<fieldset>
	<legend>Não Negatividade</legend>
	
	<ul>
		<% for i in 0..@programa_linear.numero_variavel-1 do %>
			<li>X<sub><%= i+1 %></sub>≥ 0</li>
		<% end %>
	</ul>
	
</fieldset>


<%= f.submit "Solucionar", :class => 'botao botao-azul' %>

<% end %>
</article>
</div>
<footer>
	<nav>
		<ul>
			<li><%= link_to "Voltar", home_index_path %></li>
			<li><%= link_to "Novo", programa_linear_index_path %></li>	
		</ul>	
	</nav>	
</footer>

app/views/programa_linear/solucionar_problema.html.erb
<h1>ProgramaLinear#solucionar_problema</h1>
<p>Find me in app/views/programa_linear/solucionar_problema.html.erb</p>

app/views/programa_linear/visualizar_exemplo.html.erb
<div id="container-conteudo-principal" class="azul">
<header>
	<h2>Programação Linear</h2>
	<h3>Exemplo - <%= @programa_linear.nome %></h3>
	<hr />
</header>

<article>
	
	<%= form_tag("solucionar_exemplo", :method => "get") do %>
<fieldset>	
	<legend>Programa Linear</legend>
	<%= hidden_field_tag "id", @programa_linear.id %>
	
	<%= label_tag  :nome %>
	<%= text_field_tag "nome", @programa_linear.nome, :class => 'campo-nome' %>
	<br />
	<%= label_tag  :descricao %>
	<%= text_area_tag "descricao", @programa_linear.descricao %>
	
</fieldset>
<fieldset>
	<legend>Função Objetivo</legend>
	<ul>
		<li><%= label_tag  :tipo_otimizacao %></li>
		<li><%= collection_select "otimizacao", @programa_linear.funcao_objetivo.tipo_otimizacao_id, TipoOtimizacao.all, :id, :nome %></li>
	
	
	
		<% for i in 0..@programa_linear.numero_variavel-1 do %>
	
			<li><%= text_field_tag "coeficiente", @programa_linear.funcao_objetivo.coeficiente_funcao_objetivo[i].valor %></li>
			<li>X<sub><%= i+1 %></sub></li>
	

		<% end %>
	</ul>
	
	
</fieldset>
<fieldset>
	<legend>Restrições</legend>
	
	
		<% for i in 0..@programa_linear.numero_restricao-1 do %>
			<ul>
				<%for j in 0..@programa_linear.numero_variavel-1 %>
					<li><%= text_field_tag "coeficiente", @programa_linear.restricoes[i].coeficiente_restricoes[j].valor %></li>
					<li>X<sub><%= j+1 %></sub></li>
				<% end %>
				
				<li><%= collection_select "operador_sentencial", @programa_linear.restricoes[i].operador_sentencial_id, OperadorSentencial.all, :id, :simbolo, :selected => @programa_linear.restricoes[i].operador_sentencial_id,  :disabled => true  %></li>
				<li><%= text_field_tag "constante_restricao", @programa_linear.restricoes[i].constante %></li>
			</ul>
		<% end %>
	</ul>
	
</fieldset>

<fieldset>
	<legend>Não Negatividade</legend>
	
	<ul>
		<% for i in 0..@programa_linear.numero_variavel-1 do %>
			<li>X<sub><%= i+1 %></sub>≥ 0</li>
		<% end %>
	</ul>
	
</fieldset>

<%= submit_tag "Solucionar", :class => "botao botao-azul" %>


<% end %>

</article>
</div>